"""Generador de ejemplos de mallas curriculares en formato JSON para PrereqFlow.

Crea archivos JSON válidos en examples/ listos para cargar mediante
Drag & Drop en la aplicación. Cada archivo representa un programa
académico completo de una disciplina diferente.
"""

import json
import os
from typing import Dict, List, Optional, Set, Tuple

CURRICULA: List[Dict] = []

# ──────────────────────────────────────────────
# 1. Ingeniería de Sistemas (UTP — referencia)
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "ing_sistemas_utp.json",
    "name": "Ingeniería de Sistemas y Computación — UTP",
    "courses": [
        {"code": "MAT101", "name": "Matemáticas I", "credits": 5, "semester": 1, "area": "Matemáticas"},
        {"code": "MAT102", "name": "Matemáticas II", "credits": 5, "semester": 2, "area": "Matemáticas"},
        {"code": "MAT201", "name": "Matemáticas III", "credits": 4, "semester": 3, "area": "Matemáticas"},
        {"code": "MAT202", "name": "Matemáticas IV", "credits": 3, "semester": 4, "area": "Matemáticas"},
        {"code": "MAT203", "name": "Métodos Numéricos", "credits": 4, "semester": 4, "area": "Matemáticas"},
        {"code": "ALG101", "name": "Álgebra Lineal", "credits": 4, "semester": 2, "area": "Matemáticas"},
        {"code": "EST201", "name": "Estadística", "credits": 3, "semester": 4, "area": "Estadística"},
        {"code": "EST301", "name": "Estadística Especial", "credits": 2, "semester": 6, "area": "Estadística"},
        {"code": "FIS101", "name": "Física I", "credits": 2, "semester": 2, "area": "Física"},
        {"code": "FIS102", "name": "Laboratorio de Física I", "credits": 4, "semester": 2, "area": "Física",
         "co_requisites": ["FIS101"]},
        {"code": "FIS201", "name": "Física II", "credits": 2, "semester": 3, "area": "Física"},
        {"code": "FIS202", "name": "Laboratorio de Física II", "credits": 4, "semester": 3, "area": "Física",
         "co_requisites": ["FIS201"]},
        {"code": "FIS301", "name": "Física III", "credits": 2, "semester": 4, "area": "Física"},
        {"code": "FIS302", "name": "Laboratorio de Física III", "credits": 4, "semester": 4, "area": "Física",
         "co_requisites": ["FIS301"]},
        {"code": "PRO101", "name": "Programación I", "credits": 2, "semester": 1, "area": "Computación"},
        {"code": "PRO102", "name": "Programación II", "credits": 2, "semester": 2, "area": "Computación"},
        {"code": "PRO201", "name": "Programación Orientada a Objetos", "credits": 3, "semester": 3, "area": "Computación"},
        {"code": "EST101", "name": "Estructura de Datos", "credits": 3, "semester": 3, "area": "Computación"},
        {"code": "LOG101", "name": "Lógica", "credits": 3, "semester": 3, "area": "Computación"},
        {"code": "EST102", "name": "Estructura de Lenguajes", "credits": 3, "semester": 4, "area": "Computación"},
        {"code": "COM101", "name": "Introducción a la Informática", "credits": 1, "semester": 1, "area": "Computación"},
        {"code": "BD101", "name": "Base de Datos I", "credits": 3, "semester": 5, "area": "Computación"},
        {"code": "BD201", "name": "Administración de Información", "credits": 1, "semester": 8, "area": "Gestión"},
        {"code": "ARQ101", "name": "Arquitectura de Computadores", "credits": 4, "semester": 4, "area": "Computación"},
        {"code": "SIS101", "name": "Sistemas Operativos I", "credits": 4, "semester": 6, "area": "Sistemas"},
        {"code": "SIS201", "name": "Sistemas Distribuidos", "credits": 3, "semester": 7, "area": "Sistemas"},
        {"code": "RED101", "name": "Comunicaciones I", "credits": 4, "semester": 5, "area": "Redes"},
        {"code": "RED201", "name": "Comunicaciones II", "credits": 2, "semester": 6, "area": "Redes"},
        {"code": "RED301", "name": "Comunicaciones III", "credits": 3, "semester": 8, "area": "Redes"},
        {"code": "ARQ201", "name": "Arquitectura Cliente/Servidor", "credits": 3, "semester": 8, "area": "Computación"},
        {"code": "ISW101", "name": "Ingeniería de Software I", "credits": 3, "semester": 5, "area": "Ing. Software"},
        {"code": "ISW201", "name": "Ingeniería de Software II", "credits": 3, "semester": 6, "area": "Ing. Software"},
        {"code": "ISW301", "name": "Laboratorio de Software", "credits": 3, "semester": 7, "area": "Ing. Software",
         "co_requisites": ["ISW201"]},
        {"code": "COM201", "name": "Compiladores", "credits": 3, "semester": 7, "area": "Computación"},
        {"code": "SIS301", "name": "Sistemas Expertos", "credits": 3, "semester": 9, "area": "Computación"},
        {"code": "TEC101", "name": "Nuevas Tecnologías Informáticas", "credits": 4, "semester": 8,
         "area": "Tecnologías", "elective_group": "Tecnologías Emergentes", "required": False},
        {"code": "ELE101", "name": "Electrónica I", "credits": 2, "semester": 4, "area": "Electrónica"},
        {"code": "ELE102", "name": "Laboratorio de Electrónica I", "credits": 3, "semester": 4, "area": "Electrónica",
         "co_requisites": ["ELE101"]},
        {"code": "ELE201", "name": "Electrónica II", "credits": 3, "semester": 5, "area": "Electrónica"},
        {"code": "ELE202", "name": "Laboratorio de Electrónica II", "credits": 3, "semester": 5, "area": "Electrónica",
         "co_requisites": ["ELE201"]},
        {"code": "MIC101", "name": "Microcontroladores", "credits": 3, "semester": 7, "area": "Electrónica"},
        {"code": "MIC102", "name": "Lab. Microcontroladores", "credits": 3, "semester": 7, "area": "Electrónica",
         "co_requisites": ["MIC101"]},
        {"code": "SIS401", "name": "Teoría de Sistemas", "credits": 3, "semester": 4, "area": "Ingeniería"},
        {"code": "INV101", "name": "Investigación de Operaciones", "credits": 2, "semester": 6, "area": "Gestión"},
        {"code": "ADM101", "name": "Administración de Empresas", "credits": 2, "semester": 4, "area": "Gestión"},
        {"code": "CON101", "name": "Sistemas Contables", "credits": 3, "semester": 5, "area": "Gestión"},
        {"code": "CON201", "name": "Contabilidad de Costos", "credits": 3, "semester": 6, "area": "Gestión"},
        {"code": "ECO101", "name": "Teoría Económica", "credits": 4, "semester": 5, "area": "Gestión"},
        {"code": "FIN101", "name": "Finanzas", "credits": 2, "semester": 7, "area": "Gestión"},
        {"code": "GER101", "name": "Gerencia Institucional", "credits": 2, "semester": 9, "area": "Gestión"},
        {"code": "GER201", "name": "Gerencia de Proyectos", "credits": 3, "semester": 9, "area": "Gestión"},
        {"code": "PLA101", "name": "Planeación Estratégica de Sistemas", "credits": 6, "semester": 9, "area": "Gestión"},
        {"code": "AUD101", "name": "Auditoría de Sistemas", "credits": 2, "semester": 8, "area": "Auditoría"},
        {"code": "DER101", "name": "Legislación y Ética", "credits": 1, "semester": 7, "area": "Derecho"},
        {"code": "DER201", "name": "Constitución Política", "credits": 3, "semester": 8, "area": "Derecho"},
        {"code": "HUM101", "name": "Humanidades I", "credits": 1, "semester": 1, "area": "Humanidades"},
        {"code": "HUM201", "name": "Humanidades II", "credits": 4, "semester": 3, "area": "Humanidades"},
        {"code": "COM102", "name": "Técnicas de Comunicación", "credits": 3, "semester": 1, "area": "Comunicación"},
        {"code": "DIB101", "name": "Dibujo", "credits": 4, "semester": 6, "area": "Diseño"},
        {"code": "DEP101", "name": "Deportes I", "credits": 5, "semester": 1, "area": "Formación Básica"},
        {"code": "DEP102", "name": "Deportes II", "credits": 5, "semester": 2, "area": "Formación Básica"},
        {"code": "PRO301", "name": "Proyecto de Grado I", "credits": 3, "semester": 9, "area": "Proyecto",
         "min_completed_credits": 120},
        {"code": "PRO302", "name": "Proyecto de Grado II", "credits": 3, "semester": 10, "area": "Proyecto",
         "min_completed_credits": 140},
        {"code": "SIS501", "name": "Ing. Sistemas y Computación", "credits": 2, "semester": 1, "area": "Formación Básica"},
    ],
    "prerequisites": [
        ("PRO102", "PRO101"), ("PRO201", "PRO102"), ("ISW101", "PRO201"),
        ("ISW201", "ISW101"), ("PRO301", "ISW201"), ("PRO302", "PRO301"),
        ("MAT102", "MAT101"), ("MAT201", "MAT102"), ("MAT202", "MAT201"),
        ("MAT203", "MAT202"), ("FIS201", "FIS101"), ("FIS301", "FIS201"),
        ("EST301", "EST201"), ("EST102", "EST101"), ("PRO201", "EST101"),
        ("COM201", "EST101"), ("COM201", "LOG101"),
        ("SIS201", "ARQ101"), ("SIS201", "SIS101"),
        ("BD201", "BD101"), ("BD101", "PRO102"),
        ("ARQ201", "BD101"), ("ARQ201", "SIS101"),
        ("GER201", "FIN101"), ("FIN101", "ADM101"),
        ("CON101", "CON201"), ("EST301", "EST201"),
        ("ELE201", "ELE101"), ("MIC101", "ELE201"),
        ("PRO302", "GER201"), ("RED201", "RED101"),
        ("RED301", "RED201"), ("SIS101", "ARQ101"),
        ("ARQ101", "EST101"), ("PRO101", "COM101"),
        ("PRO101", "MAT101"), ("FIS101", "MAT102"),
        ("ALG101", "MAT101"), ("FIS201", "ALG101"),
        ("MAT201", "MAT102"), ("MAT202", "MAT201"),
        ("PRO201", "PRO102"), ("EST101", "PRO102"),
        ("SIS401", "MAT201"), ("INV101", "EST201"),
    ],
    "co_requisites": [
        ("FIS101", "FIS102"), ("FIS201", "FIS202"),
        ("FIS301", "FIS302"), ("ELE101", "ELE102"),
        ("ELE201", "ELE202"), ("MIC101", "MIC102"),
        ("ISW201", "ISW301"),
    ],
})

# ──────────────────────────────────────────────
# 2. Medicina
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "medicina.json",
    "name": "Medicina — Facultad de Ciencias de la Salud",
    "courses": [
        {"code": "ANA101", "name": "Anatomía Humana I", "credits": 6, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "ANA102", "name": "Anatomía Humana II", "credits": 6, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "HIS101", "name": "Histología", "credits": 4, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "EMB101", "name": "Embriología", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "BIO101", "name": "Biología Celular y Molecular", "credits": 5, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "QUI101", "name": "Bioquímica I", "credits": 5, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "QUI102", "name": "Bioquímica II", "credits": 4, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "FIS101", "name": "Fisiología I", "credits": 5, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "FIS102", "name": "Fisiología II", "credits": 5, "semester": 3, "area": "Ciencias Básicas"},
        {"code": "FAR101", "name": "Farmacología I", "credits": 4, "semester": 4, "area": "Ciencias Clínicas"},
        {"code": "FAR102", "name": "Farmacología II", "credits": 4, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "PAT101", "name": "Patología General", "credits": 5, "semester": 3, "area": "Ciencias Clínicas"},
        {"code": "PAT102", "name": "Patología Sistémica", "credits": 5, "semester": 4, "area": "Ciencias Clínicas"},
        {"code": "MIC101", "name": "Microbiología", "credits": 4, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "PAR101", "name": "Parasitología", "credits": 3, "semester": 3, "area": "Ciencias Básicas"},
        {"code": "INM101", "name": "Inmunología", "credits": 3, "semester": 3, "area": "Ciencias Básicas"},
        {"code": "SEM101", "name": "Semiología I", "credits": 5, "semester": 4, "area": "Ciencias Clínicas"},
        {"code": "SEM102", "name": "Semiología II", "credits": 5, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "MED101", "name": "Medicina Interna I", "credits": 6, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "MED102", "name": "Medicina Interna II", "credits": 6, "semester": 6, "area": "Ciencias Clínicas"},
        {"code": "CIR101", "name": "Cirugía General I", "credits": 6, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "CIR102", "name": "Cirugía General II", "credits": 6, "semester": 6, "area": "Ciencias Clínicas"},
        {"code": "PED101", "name": "Pediatría", "credits": 5, "semester": 6, "area": "Ciencias Clínicas"},
        {"code": "GIN101", "name": "Ginecología y Obstetricia", "credits": 5, "semester": 6, "area": "Ciencias Clínicas"},
        {"code": "PSI101", "name": "Psiquiatría", "credits": 4, "semester": 7, "area": "Ciencias Clínicas"},
        {"code": "DER101", "name": "Dermatología", "credits": 3, "semester": 7, "area": "Ciencias Clínicas"},
        {"code": "OFT101", "name": "Oftalmología", "credits": 3, "semester": 7, "area": "Ciencias Clínicas"},
        {"code": "OTO101", "name": "Otorrinolaringología", "credits": 3, "semester": 7, "area": "Ciencias Clínicas"},
        {"code": "TRA101", "name": "Traumatología", "credits": 4, "semester": 7, "area": "Ciencias Clínicas"},
        {"code": "ANE101", "name": "Anestesiología", "credits": 3, "semester": 8, "area": "Ciencias Clínicas"},
        {"code": "IMG101", "name": "Imagenología", "credits": 3, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "MED103", "name": "Medicina de Urgencias", "credits": 4, "semester": 8, "area": "Ciencias Clínicas"},
        {"code": "MED201", "name": "Medicina Preventiva", "credits": 3, "semester": 4, "area": "Salud Pública"},
        {"code": "SAL101", "name": "Salud Pública I", "credits": 3, "semester": 3, "area": "Salud Pública"},
        {"code": "SAL102", "name": "Salud Pública II", "credits": 3, "semester": 4, "area": "Salud Pública"},
        {"code": "EPI101", "name": "Epidemiología", "credits": 3, "semester": 4, "area": "Salud Pública"},
        {"code": "BIO201", "name": "Bioética", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "INV101", "name": "Metodología de la Investigación", "credits": 3, "semester": 5,
         "area": "Ciencias Básicas"},
        {"code": "ROT101", "name": "Internado Rotatorio I", "credits": 10, "semester": 9, "area": "Internado"},
        {"code": "ROT102", "name": "Internado Rotatorio II", "credits": 10, "semester": 10, "area": "Internado"},
        {"code": "ROT103", "name": "Internado Rotatorio III", "credits": 10, "semester": 11, "area": "Internado"},
        {"code": "ROT104", "name": "Internado Rotatorio IV", "credits": 10, "semester": 12, "area": "Internado"},
        {"code": "MED301", "name": "Medicina Legal", "credits": 2, "semester": 8, "area": "Ciencias Clínicas"},
        {"code": "NU101", "name": "Nutrición Clínica", "credits": 2, "semester": 5, "area": "Ciencias Clínicas"},
        {"code": "PSI201", "name": "Psicología Médica", "credits": 2, "semester": 3, "area": "Ciencias Básicas"},
    ],
    "prerequisites": [
        ("ANA102", "ANA101"), ("QUI102", "QUI101"),
        ("FIS101", "QUI102"), ("FIS101", "ANA102"),
        ("FIS102", "FIS101"), ("PAT101", "HIS101"),
        ("PAT101", "FIS101"), ("PAT102", "PAT101"),
        ("FAR101", "FIS101"), ("FAR102", "FAR101"),
        ("PAR101", "MIC101"), ("INM101", "BIO101"),
        ("SEM101", "FIS102"), ("SEM101", "PAT102"),
        ("SEM102", "SEM101"), ("MED101", "SEM102"),
        ("MED102", "MED101"), ("CIR101", "SEM102"),
        ("CIR102", "CIR101"), ("PED101", "MED101"),
        ("GIN101", "MED101"), ("TRA101", "CIR101"),
        ("ANE101", "CIR102"), ("MED103", "MED102"),
        ("MED201", "SAL101"), ("SAL102", "SAL101"),
        ("EPI101", "SAL101"), ("IMG101", "SEM101"),
        ("ROT101", "MED102"), ("ROT101", "CIR102"),
        ("ROT102", "ROT101"), ("ROT103", "ROT102"),
        ("ROT104", "ROT103"), ("PSI101", "SEM102"),
        ("DER101", "SEM102"), ("OFT101", "SEM102"),
        ("OTO101", "SEM102"), ("MED301", "SEM102"),
        ("NU101", "BIO101"), ("PSI201", "BIO101"),
        ("INV101", "EPI101"), ("SAL101", "MIC101"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 3. Derecho
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "derecho.json",
    "name": "Derecho — Facultad de Ciencias Jurídicas",
    "courses": [
        {"code": "DER101", "name": "Introducción al Derecho", "credits": 4, "semester": 1, "area": "Fundamentos"},
        {"code": "DER102", "name": "Historia del Derecho", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "DER103", "name": "Teoría del Estado", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "DER104", "name": "Sociología Jurídica", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "DER105", "name": "Metodología del Estudio del Derecho", "credits": 2, "semester": 1,
         "area": "Fundamentos"},
        {"code": "DER201", "name": "Derecho Romano", "credits": 3, "semester": 2, "area": "Fundamentos"},
        {"code": "DER202", "name": "Derecho Constitucional General", "credits": 4, "semester": 2, "area": "Público"},
        {"code": "DER203", "name": "Derecho Penal General", "credits": 4, "semester": 2, "area": "Penal"},
        {"code": "DER204", "name": "Economía Política", "credits": 3, "semester": 2, "area": "Fundamentos"},
        {"code": "DER301", "name": "Derecho Constitucional Colombiano", "credits": 4, "semester": 3, "area": "Público"},
        {"code": "DER302", "name": "Derecho Penal Especial", "credits": 4, "semester": 3, "area": "Penal"},
        {"code": "DER303", "name": "Teoría General del Proceso", "credits": 4, "semester": 3, "area": "Procesal"},
        {"code": "DER304", "name": "Bienes", "credits": 3, "semester": 3, "area": "Privado"},
        {"code": "DER401", "name": "Derecho Procesal Penal", "credits": 4, "semester": 4, "area": "Procesal"},
        {"code": "DER402", "name": "Obligaciones", "credits": 4, "semester": 4, "area": "Privado"},
        {"code": "DER403", "name": "Contratos", "credits": 4, "semester": 4, "area": "Privado"},
        {"code": "DER404", "name": "Derecho Administrativo General", "credits": 3, "semester": 4, "area": "Público"},
        {"code": "DER501", "name": "Derecho Procesal Civil", "credits": 4, "semester": 5, "area": "Procesal"},
        {"code": "DER502", "name": "Derecho Laboral Individual", "credits": 3, "semester": 5, "area": "Laboral"},
        {"code": "DER503", "name": "Derecho Administrativo Especial", "credits": 3, "semester": 5, "area": "Público"},
        {"code": "DER504", "name": "Derecho Comercial General", "credits": 3, "semester": 5, "area": "Privado"},
        {"code": "DER601", "name": "Derecho Procesal Administrativo", "credits": 3, "semester": 6, "area": "Procesal"},
        {"code": "DER602", "name": "Derecho Laboral Colectivo", "credits": 3, "semester": 6, "area": "Laboral"},
        {"code": "DER603", "name": "Sociedades Comerciales", "credits": 3, "semester": 6, "area": "Privado"},
        {"code": "DER604", "name": "Títulos Valores", "credits": 3, "semester": 6, "area": "Privado"},
        {"code": "DER701", "name": "Derecho Internacional Público", "credits": 3, "semester": 7, "area": "Público"},
        {"code": "DER702", "name": "Derecho de Familia", "credits": 3, "semester": 7, "area": "Privado"},
        {"code": "DER703", "name": "Sucesiones", "credits": 3, "semester": 7, "area": "Privado"},
        {"code": "DER704", "name": "Derecho Minero y Ambiental", "credits": 2, "semester": 7, "area": "Público"},
        {"code": "DER801", "name": "Derecho Internacional Privado", "credits": 3, "semester": 8, "area": "Privado"},
        {"code": "DER802", "name": "Derecho Tributario", "credits": 3, "semester": 8, "area": "Público"},
        {"code": "DER803", "name": "Filosofía del Derecho", "credits": 3, "semester": 8, "area": "Fundamentos"},
        {"code": "DER804", "name": "Práctica Forense Civil", "credits": 3, "semester": 8, "area": "Práctica"},
        {"code": "DER901", "name": "Práctica Forense Penal", "credits": 3, "semester": 9, "area": "Práctica"},
        {"code": "DER902", "name": "Práctica Forense Laboral", "credits": 3, "semester": 9, "area": "Práctica"},
        {"code": "DER903", "name": "Práctica Forense Administrativa", "credits": 3, "semester": 9, "area": "Práctica"},
        {"code": "DER904", "name": "Consulta y Asesoría Jurídica", "credits": 4, "semester": 9, "area": "Práctica"},
        {"code": "DER905", "name": "Monografía Jurídica", "credits": 4, "semester": 9, "area": "Investigación"},
        {"code": "DER906", "name": "Ética Profesional del Abogado", "credits": 2, "semester": 9, "area": "Fundamentos"},
        {"code": "DER307", "name": "Hermenéutica Jurídica", "credits": 2, "semester": 3, "area": "Fundamentos"},
        {"code": "DER505", "name": "Medicina Legal Forense", "credits": 2, "semester": 5, "area": "Penal"},
        {"code": "DER506", "name": "Criminología", "credits": 3, "semester": 5, "area": "Penal"},
        {"code": "DER507", "name": "Régimen de la Propiedad Inmueble", "credits": 3, "semester": 5, "area": "Privado"},
    ],
    "prerequisites": [
        ("DER201", "DER101"), ("DER202", "DER101"),
        ("DER203", "DER101"), ("DER301", "DER202"),
        ("DER302", "DER203"), ("DER303", "DER201"),
        ("DER304", "DER201"), ("DER401", "DER303"),
        ("DER401", "DER302"), ("DER402", "DER304"),
        ("DER403", "DER402"), ("DER404", "DER202"),
        ("DER501", "DER303"), ("DER502", "DER203"),
        ("DER503", "DER404"), ("DER504", "DER402"),
        ("DER601", "DER503"), ("DER602", "DER502"),
        ("DER603", "DER504"), ("DER604", "DER504"),
        ("DER701", "DER301"), ("DER801", "DER701"),
        ("DER702", "DER402"), ("DER703", "DER402"),
        ("DER802", "DER503"), ("DER803", "DER102"),
        ("DER804", "DER501"), ("DER901", "DER401"),
        ("DER902", "DER602"), ("DER903", "DER601"),
        ("DER905", "DER803"), ("DER307", "DER101"),
        ("DER505", "DER203"), ("DER506", "DER302"),
        ("DER507", "DER304"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 4. Administración de Empresas
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "administracion_empresas.json",
    "name": "Administración de Empresas — Facultad de Ciencias Económicas",
    "courses": [
        {"code": "ADM101", "name": "Fundamentos de Administración", "credits": 3, "semester": 1, "area": "Administración"},
        {"code": "ADM102", "name": "Teoría de las Organizaciones", "credits": 3, "semester": 1, "area": "Administración"},
        {"code": "CON101", "name": "Contabilidad General", "credits": 4, "semester": 1, "area": "Contabilidad"},
        {"code": "ECO101", "name": "Principios de Economía", "credits": 3, "semester": 1, "area": "Economía"},
        {"code": "MAT101", "name": "Matemáticas Básicas", "credits": 3, "semester": 1, "area": "Matemáticas"},
        {"code": "COM101", "name": "Comunicación Empresarial", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "MAT102", "name": "Matemáticas Financieras", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "EST101", "name": "Estadística Descriptiva", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "CON102", "name": "Contabilidad de Costos", "credits": 4, "semester": 2, "area": "Contabilidad"},
        {"code": "MIC101", "name": "Microeconomía", "credits": 3, "semester": 2, "area": "Economía"},
        {"code": "DER101", "name": "Derecho Comercial", "credits": 2, "semester": 2, "area": "Derecho"},
        {"code": "EST102", "name": "Estadística Inferencial", "credits": 3, "semester": 3, "area": "Matemáticas"},
        {"code": "MAC101", "name": "Macroeconomía", "credits": 3, "semester": 3, "area": "Economía"},
        {"code": "CON201", "name": "Contabilidad Financiera", "credits": 4, "semester": 3, "area": "Contabilidad"},
        {"code": "MER101", "name": "Fundamentos de Marketing", "credits": 3, "semester": 3, "area": "Mercadeo"},
        {"code": "ADM201", "name": "Gestión del Talento Humano", "credits": 3, "semester": 3, "area": "Administración"},
        {"code": "FIN101", "name": "Finanzas Corporativas", "credits": 4, "semester": 4, "area": "Finanzas"},
        {"code": "MER201", "name": "Investigación de Mercados", "credits": 3, "semester": 4, "area": "Mercadeo"},
        {"code": "ADM301", "name": "Gerencia Estratégica", "credits": 4, "semester": 4, "area": "Administración"},
        {"code": "PRO101", "name": "Gestión de Procesos", "credits": 3, "semester": 4, "area": "Operaciones"},
        {"code": "DER201", "name": "Derecho Laboral", "credits": 2, "semester": 4, "area": "Derecho"},
        {"code": "FIN201", "name": "Mercado de Capitales", "credits": 3, "semester": 5, "area": "Finanzas"},
        {"code": "PRO201", "name": "Gestión de la Cadena de Suministro", "credits": 3, "semester": 5, "area": "Operaciones"},
        {"code": "ADM401", "name": "Emprendimiento e Innovación", "credits": 3, "semester": 5, "area": "Administración"},
        {"code": "MER301", "name": "Marketing Digital", "credits": 3, "semester": 5, "area": "Mercadeo"},
        {"code": "CON301", "name": "Análisis Financiero", "credits": 3, "semester": 5, "area": "Contabilidad"},
        {"code": "INV101", "name": "Investigación de Operaciones", "credits": 3, "semester": 5, "area": "Matemáticas"},
        {"code": "ADM501", "name": "Gerencia de Proyectos", "credits": 3, "semester": 6, "area": "Administración"},
        {"code": "FIN301", "name": "Evaluación de Proyectos", "credits": 3, "semester": 6, "area": "Finanzas"},
        {"code": "MER401", "name": "Gerencia de Ventas", "credits": 3, "semester": 6, "area": "Mercadeo"},
        {"code": "ADM601", "name": "Gestión de la Calidad", "credits": 3, "semester": 6, "area": "Operaciones"},
        {"code": "AUD101", "name": "Auditoría Administrativa", "credits": 3, "semester": 6, "area": "Auditoría"},
        {"code": "ADM701", "name": "Responsabilidad Social Empresarial", "credits": 2, "semester": 7, "area": "Administración"},
        {"code": "INT101", "name": "Negocios Internacionales", "credits": 3, "semester": 7, "area": "Administración"},
        {"code": "ADM801", "name": "Práctica Profesional", "credits": 6, "semester": 7, "area": "Práctica"},
        {"code": "ADM901", "name": "Seminario de Grado", "credits": 4, "semester": 8, "area": "Investigación"},
        {"code": "ETI101", "name": "Ética Empresarial", "credits": 2, "semester": 3, "area": "Humanidades"},
        {"code": "HUM101", "name": "Humanidades I", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "HUM102", "name": "Humanidades II", "credits": 2, "semester": 2, "area": "Humanidades"},
        {"code": "ING101", "name": "Inglés de Negocios I", "credits": 2, "semester": 1, "area": "Idiomas"},
        {"code": "ING102", "name": "Inglés de Negocios II", "credits": 2, "semester": 2, "area": "Idiomas"},
        {"code": "ING201", "name": "Inglés de Negocios III", "credits": 2, "semester": 3, "area": "Idiomas"},
        {"code": "ING202", "name": "Inglés de Negocios IV", "credits": 2, "semester": 4, "area": "Idiomas"},
        {"code": "TRI101", "name": "Tributación", "credits": 3, "semester": 6, "area": "Derecho"},
        {"code": "ADM100", "name": "Habilidades Gerenciales", "credits": 2, "semester": 2, "area": "Administración"},
    ],
    "prerequisites": [
        ("MAT102", "MAT101"), ("EST101", "MAT101"),
        ("CON102", "CON101"), ("MIC101", "ECO101"),
        ("EST102", "EST101"), ("MAC101", "ECO101"),
        ("CON201", "CON102"), ("ADM201", "ADM101"),
        ("FIN101", "MAT102"), ("FIN101", "CON201"),
        ("MER201", "MER101"), ("ADM301", "ADM201"),
        ("DER201", "DER101"), ("FIN201", "FIN101"),
        ("PRO201", "PRO101"), ("CON301", "CON201"),
        ("INV101", "EST102"), ("ADM501", "ADM301"),
        ("FIN301", "FIN101"), ("MER401", "MER201"),
        ("TRI101", "DER101"), ("INT101", "MAC101"),
        ("ADM901", "ADM501"), ("ING102", "ING101"),
        ("ING201", "ING102"), ("ING202", "ING201"),
        ("HUM102", "HUM101"), ("ADM100", "ADM101"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 5. Psicología
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "psicologia.json",
    "name": "Psicología — Facultad de Ciencias Sociales",
    "courses": [
        {"code": "PSI101", "name": "Introducción a la Psicología", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "PSI102", "name": "Historia de la Psicología", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "BIO101", "name": "Biología del Comportamiento", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "SOC101", "name": "Sociología General", "credits": 3, "semester": 1, "area": "Ciencias Sociales"},
        {"code": "MAT101", "name": "Estadística Descriptiva", "credits": 3, "semester": 1, "area": "Metodología"},
        {"code": "COM101", "name": "Competencias Comunicativas", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "PSI201", "name": "Psicología del Desarrollo I", "credits": 3, "semester": 2, "area": "Ciclo Vital"},
        {"code": "PSI202", "name": "Psicología del Desarrollo II", "credits": 3, "semester": 3, "area": "Ciclo Vital"},
        {"code": "PSI203", "name": "Neuropsicología", "credits": 4, "semester": 2, "area": "Biológica"},
        {"code": "PSI204", "name": "Teorías de la Personalidad", "credits": 3, "semester": 2, "area": "Fundamentos"},
        {"code": "PSI205", "name": "Psicología Cognitiva", "credits": 3, "semester": 2, "area": "Fundamentos"},
        {"code": "MAT102", "name": "Estadística Inferencial", "credits": 3, "semester": 2, "area": "Metodología"},
        {"code": "PSI301", "name": "Psicología del Aprendizaje", "credits": 3, "semester": 3, "area": "Fundamentos"},
        {"code": "PSI302", "name": "Psicología Social", "credits": 3, "semester": 3, "area": "Social"},
        {"code": "PSI303", "name": " Psicología Educativa", "credits": 3, "semester": 3, "area": "Aplicada"},
        {"code": "MET101", "name": "Métodos de Investigación I", "credits": 3, "semester": 3, "area": "Metodología"},
        {"code": "PSI401", "name": "Psicología Clínica", "credits": 4, "semester": 4, "area": "Clínica"},
        {"code": "PSI402", "name": "Psicología Organizacional", "credits": 3, "semester": 4, "area": "Organizacional"},
        {"code": "PSI403", "name": "Psicometría", "credits": 4, "semester": 4, "area": "Metodología"},
        {"code": "MET102", "name": "Métodos de Investigación II", "credits": 3, "semester": 4, "area": "Metodología"},
        {"code": "PSI501", "name": "Evaluación Psicológica I", "credits": 4, "semester": 5, "area": "Clínica"},
        {"code": "PSI502", "name": "Psicopatología", "credits": 4, "semester": 5, "area": "Clínica"},
        {"code": "PSI503", "name": "Selección y Evaluación de Personal", "credits": 3, "semester": 5,
         "area": "Organizacional"},
        {"code": "PSI504", "name": "Psicología de la Salud", "credits": 3, "semester": 5, "area": "Salud"},
        {"code": "PSI601", "name": "Evaluación Psicológica II", "credits": 4, "semester": 6, "area": "Clínica"},
        {"code": "PSI602", "name": "Modelos de Intervención Psicológica", "credits": 4, "semester": 6, "area": "Clínica"},
        {"code": "PSI603", "name": "Capacitación y Desarrollo", "credits": 3, "semester": 6, "area": "Organizacional"},
        {"code": "PSI604", "name": "Psicología Comunitaria", "credits": 3, "semester": 6, "area": "Social"},
        {"code": "PSI701", "name": "Terapia Cognitivo-Conductual", "credits": 4, "semester": 7, "area": "Clínica"},
        {"code": "PSI702", "name": "Psicología de la Familia", "credits": 3, "semester": 7, "area": "Clínica"},
        {"code": "PSI703", "name": "Salud Ocupacional", "credits": 3, "semester": 7, "area": "Organizacional"},
        {"code": "ETI101", "name": "Ética Profesional del Psicólogo", "credits": 2, "semester": 5, "area": "Fundamentos"},
        {"code": "PSI704", "name": "Práctica Profesional I", "credits": 6, "semester": 8, "area": "Práctica"},
        {"code": "PSI705", "name": "Práctica Profesional II", "credits": 6, "semester": 9, "area": "Práctica"},
        {"code": "PSI801", "name": "Trabajo de Grado", "credits": 6, "semester": 9, "area": "Investigación"},
        {"code": "PSI306", "name": "Psicología Diferencial", "credits": 2, "semester": 3, "area": "Fundamentos"},
        {"code": "PSI404", "name": "Psicofarmacología", "credits": 3, "semester": 4, "area": "Biológica"},
        {"code": "PSI505", "name": "Neuropsicología Clínica", "credits": 3, "semester": 5, "area": "Biológica"},
        {"code": "PSI605", "name": "Psicología Jurídica", "credits": 3, "semester": 6, "area": "Aplicada"},
        {"code": "PSI706", "name": "Psicología del Consumidor", "credits": 3, "semester": 7, "area": "Organizacional"},
    ],
    "prerequisites": [
        ("PSI201", "PSI101"), ("PSI202", "PSI201"),
        ("PSI203", "BIO101"), ("PSI204", "PSI101"),
        ("PSI205", "PSI101"), ("MAT102", "MAT101"),
        ("PSI301", "PSI205"), ("PSI302", "SOC101"),
        ("PSI303", "PSI201"), ("MET101", "MAT102"),
        ("PSI401", "PSI204"), ("PSI402", "PSI302"),
        ("PSI403", "MAT102"), ("MET102", "MET101"),
        ("PSI501", "PSI403"), ("PSI502", "PSI401"),
        ("PSI503", "PSI402"), ("PSI504", "PSI301"),
        ("PSI601", "PSI501"), ("PSI602", "PSI502"),
        ("PSI603", "PSI503"), ("PSI604", "PSI302"),
        ("PSI701", "PSI602"), ("PSI702", "PSI601"),
        ("PSI703", "PSI402"), ("PSI704", "PSI602"),
        ("PSI704", "PSI603"), ("PSI705", "PSI704"),
        ("PSI801", "MET102"), ("PSI404", "PSI203"),
        ("PSI505", "PSI404"), ("PSI605", "PSI302"),
        ("PSI706", "PSI503"), ("ETI101", "PSI401"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 6. Ingeniería Civil
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "ingenieria_civil.json",
    "name": "Ingeniería Civil — Facultad de Ingeniería",
    "courses": [
        {"code": "MAT101", "name": "Cálculo Diferencial", "credits": 4, "semester": 1, "area": "Matemáticas"},
        {"code": "MAT102", "name": "Cálculo Integral", "credits": 4, "semester": 2, "area": "Matemáticas"},
        {"code": "MAT201", "name": "Cálculo Vectorial", "credits": 4, "semester": 3, "area": "Matemáticas"},
        {"code": "MAT202", "name": "Ecuaciones Diferenciales", "credits": 4, "semester": 4, "area": "Matemáticas"},
        {"code": "ALG101", "name": "Álgebra Lineal", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "FIS101", "name": "Física Mecánica", "credits": 4, "semester": 1, "area": "Física"},
        {"code": "FIS102", "name": "Física Eléctrica", "credits": 4, "semester": 2, "area": "Física"},
        {"code": "FIS103", "name": "Física de Ondas", "credits": 4, "semester": 3, "area": "Física"},
        {"code": "QUI101", "name": "Química General", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "DIB101", "name": "Dibujo de Ingeniería", "credits": 3, "semester": 1, "area": "Ingeniería"},
        {"code": "DIB102", "name": "Dibujo Asistido por Computador", "credits": 3, "semester": 2, "area": "Ingeniería"},
        {"code": "EST101", "name": "Estática", "credits": 3, "semester": 2, "area": "Ingeniería"},
        {"code": "EST102", "name": "Dinámica", "credits": 3, "semester": 3, "area": "Ingeniería"},
        {"code": "MAT203", "name": "Mecánica de Sólidos", "credits": 4, "semester": 3, "area": "Ingeniería"},
        {"code": "MAT301", "name": "Mecánica de Fluidos", "credits": 4, "semester": 4, "area": "Ingeniería"},
        {"code": "GEO101", "name": "Geología para Ingenieros", "credits": 3, "semester": 3, "area": "Ingeniería"},
        {"code": "TOP101", "name": "Topografía", "credits": 4, "semester": 3, "area": "Ingeniería"},
        {"code": "MAT401", "name": "Resistencia de Materiales", "credits": 4, "semester": 4, "area": "Ingeniería"},
        {"code": "MAT402", "name": "Análisis Estructural I", "credits": 4, "semester": 5, "area": "Estructural"},
        {"code": "MAT501", "name": "Análisis Estructural II", "credits": 4, "semester": 6, "area": "Estructural"},
        {"code": "HID101", "name": "Hidráulica", "credits": 4, "semester": 5, "area": "Hidráulica"},
        {"code": "HID102", "name": "Hidrología", "credits": 3, "semester": 5, "area": "Hidráulica"},
        {"code": "SUE101", "name": "Mecánica de Suelos", "credits": 4, "semester": 5, "area": "Geotecnia"},
        {"code": "SUE102", "name": "Cimentaciones", "credits": 4, "semester": 6, "area": "Geotecnia"},
        {"code": "MAT601", "name": "Diseño de Estructuras de Concreto", "credits": 4, "semester": 6, "area": "Estructural"},
        {"code": "MAT602", "name": "Diseño de Estructuras Metálicas", "credits": 4, "semester": 7, "area": "Estructural"},
        {"code": "MAT701", "name": "Puentes", "credits": 3, "semester": 8, "area": "Estructural"},
        {"code": "CIV101", "name": "Materiales de Construcción", "credits": 3, "semester": 4, "area": "Ingeniería"},
        {"code": "CIV201", "name": "Construcción Pesada", "credits": 3, "semester": 6, "area": "Construcción"},
        {"code": "CIV301", "name": "Gestión de la Construcción", "credits": 3, "semester": 7, "area": "Construcción"},
        {"code": "CIV401", "name": "Vías y Transporte", "credits": 4, "semester": 6, "area": "Transporte"},
        {"code": "CIV402", "name": "Diseño de Pavimentos", "credits": 3, "semester": 7, "area": "Transporte"},
        {"code": "CIV501", "name": "Ingeniería de Tránsito", "credits": 3, "semester": 7, "area": "Transporte"},
        {"code": "CIV502", "name": "Acueductos y Alcantarillados", "credits": 4, "semester": 7, "area": "Hidráulica"},
        {"code": "CIV503", "name": "Obras Hidráulicas", "credits": 3, "semester": 8, "area": "Hidráulica"},
        {"code": "CIV601", "name": "Ingeniería Sísmica", "credits": 3, "semester": 8, "area": "Estructural"},
        {"code": "CIV701", "name": "Evaluación de Proyectos", "credits": 3, "semester": 8, "area": "Gestión"},
        {"code": "CIV801", "name": "Práctica Profesional", "credits": 6, "semester": 9, "area": "Práctica"},
        {"code": "CIV901", "name": "Proyecto de Grado", "credits": 6, "semester": 10, "area": "Investigación"},
        {"code": "EST103", "name": "Estadística", "credits": 3, "semester": 3, "area": "Matemáticas"},
        {"code": "ADM101", "name": "Administración de Obras", "credits": 2, "semester": 8, "area": "Gestión"},
        {"code": "AMB101", "name": "Ingeniería Ambiental", "credits": 2, "semester": 5, "area": "Ambiental"},
        {"code": "LEG101", "name": "Legislación en Construcción", "credits": 2, "semester": 7, "area": "Derecho"},
    ],
    "prerequisites": [
        ("MAT102", "MAT101"), ("MAT201", "MAT102"),
        ("MAT202", "MAT201"), ("ALG101", "MAT101"),
        ("FIS102", "FIS101"), ("FIS103", "FIS102"),
        ("DIB102", "DIB101"), ("EST101", "FIS101"),
        ("EST101", "MAT101"), ("EST102", "EST101"),
        ("MAT203", "MAT101"), ("MAT301", "MAT202"),
        ("MAT301", "FIS102"), ("GEO101", "QUI101"),
        ("TOP101", "DIB102"), ("MAT401", "MAT203"),
        ("MAT402", "MAT401"), ("MAT501", "MAT402"),
        ("HID101", "MAT301"), ("HID102", "EST103"),
        ("SUE101", "GEO101"), ("SUE102", "SUE101"),
        ("MAT601", "MAT402"), ("MAT602", "MAT501"),
        ("MAT701", "MAT601"), ("CIV101", "QUI101"),
        ("CIV201", "CIV101"), ("CIV301", "CIV201"),
        ("CIV401", "TOP101"), ("CIV402", "CIV401"),
        ("CIV501", "CIV401"), ("CIV502", "HID101"),
        ("CIV503", "CIV502"), ("CIV601", "MAT602"),
        ("CIV701", "CIV301"), ("CIV901", "CIV801"),
        ("EST103", "MAT102"), ("AMB101", "QUI101"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 7. Arquitectura
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "arquitectura.json",
    "name": "Arquitectura — Facultad de Artes y Diseño",
    "courses": [
        {"code": "ARQ101", "name": "Introducción a la Arquitectura", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "ARQ102", "name": "Historia del Arte y la Arquitectura I", "credits": 3, "semester": 1,
         "area": "Teoría e Historia"},
        {"code": "ARQ103", "name": "Taller de Diseño Básico I", "credits": 6, "semester": 1, "area": "Diseño"},
        {"code": "ARQ104", "name": "Geometría Descriptiva", "credits": 3, "semester": 1, "area": "Representación"},
        {"code": "ARQ105", "name": "Dibujo Arquitectónico a Mano Alzada", "credits": 3, "semester": 1,
         "area": "Representación"},
        {"code": "MAT101", "name": "Matemáticas Básicas", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "ARQ201", "name": "Historia de la Arquitectura II", "credits": 3, "semester": 2, "area": "Teoría e Historia"},
        {"code": "ARQ202", "name": "Taller de Diseño Básico II", "credits": 6, "semester": 2, "area": "Diseño"},
        {"code": "ARQ203", "name": "Sistemas de Representación Gráfica", "credits": 3, "semester": 2,
         "area": "Representación"},
        {"code": "ARQ204", "name": "Introducción a los Materiales", "credits": 3, "semester": 2, "area": "Tecnología"},
        {"code": "ARQ301", "name": "Historia de la Arquitectura III", "credits": 3, "semester": 3, "area": "Teoría e Historia"},
        {"code": "ARQ302", "name": "Taller de Diseño Arquitectónico I", "credits": 6, "semester": 3, "area": "Diseño"},
        {"code": "ARQ303", "name": "Estructuras I", "credits": 4, "semester": 3, "area": "Tecnología"},
        {"code": "ARQ304", "name": "Topografía y Contexto Urbano", "credits": 3, "semester": 3, "area": "Urbanismo"},
        {"code": "FIS101", "name": "Física de las Construcciones", "credits": 3, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "ARQ401", "name": "Teoría de la Arquitectura", "credits": 3, "semester": 4, "area": "Teoría e Historia"},
        {"code": "ARQ402", "name": "Taller de Diseño Arquitectónico II", "credits": 6, "semester": 4, "area": "Diseño"},
        {"code": "ARQ403", "name": "Estructuras II", "credits": 4, "semester": 4, "area": "Tecnología"},
        {"code": "ARQ404", "name": "Instalaciones Hidrosanitarias", "credits": 3, "semester": 4, "area": "Tecnología"},
        {"code": "ARQ501", "name": "Taller de Diseño Urbano", "credits": 6, "semester": 5, "area": "Urbanismo"},
        {"code": "ARQ502", "name": "Estructuras III", "credits": 4, "semester": 5, "area": "Tecnología"},
        {"code": "ARQ503", "name": "Instalaciones Eléctricas", "credits": 3, "semester": 5, "area": "Tecnología"},
        {"code": "ARQ504", "name": "Planificación Urbana", "credits": 3, "semester": 5, "area": "Urbanismo"},
        {"code": "ARQ601", "name": "Taller de Diseño Arquitectónico III", "credits": 6, "semester": 6, "area": "Diseño"},
        {"code": "ARQ602", "name": "Acondicionamiento Ambiental", "credits": 3, "semester": 6, "area": "Tecnología"},
        {"code": "ARQ603", "name": "Presupuesto y Programación de Obras", "credits": 3, "semester": 6, "area": "Gestión"},
        {"code": "ARQ604", "name": "Legislación Urbana", "credits": 2, "semester": 6, "area": "Urbanismo"},
        {"code": "ARQ701", "name": "Taller de Diseño Arquitectónico IV", "credits": 6, "semester": 7, "area": "Diseño"},
        {"code": "ARQ702", "name": "Restauración y Patrimonio", "credits": 3, "semester": 7, "area": "Teoría e Historia"},
        {"code": "ARQ703", "name": "Gerencia de Proyectos Arquitectónicos", "credits": 3, "semester": 7, "area": "Gestión"},
        {"code": "ARQ801", "name": "Taller de Diseño Arquitectónico V", "credits": 6, "semester": 8, "area": "Diseño"},
        {"code": "ARQ802", "name": "Sostenibilidad y Bioclimática", "credits": 3, "semester": 8, "area": "Tecnología"},
        {"code": "ARQ803", "name": "Práctica Profesional", "credits": 4, "semester": 8, "area": "Práctica"},
        {"code": "ARQ901", "name": "Taller de Grado", "credits": 8, "semester": 9, "area": "Diseño"},
        {"code": "ARQ902", "name": "Ética y Responsabilidad Profesional", "credits": 2, "semester": 7, "area": "Humanidades"},
        {"code": "ARQ305", "name": "Urbanismo I", "credits": 3, "semester": 3, "area": "Urbanismo"},
        {"code": "ARQ405", "name": "Urbanismo II", "credits": 3, "semester": 4, "area": "Urbanismo"},
        {"code": "ARQ505", "name": "Paisajismo", "credits": 3, "semester": 5, "area": "Urbanismo"},
        {"code": "SOC101", "name": "Sociología Urbana", "credits": 2, "semester": 4, "area": "Humanidades"},
        {"code": "ING101", "name": "Modelado Digital 3D", "credits": 3, "semester": 4, "area": "Representación"},
    ],
    "prerequisites": [
        ("ARQ201", "ARQ102"), ("ARQ202", "ARQ103"),
        ("ARQ203", "ARQ104"), ("ARQ204", "ARQ105"),
        ("ARQ301", "ARQ201"), ("ARQ302", "ARQ202"),
        ("ARQ303", "FIS101"), ("ARQ304", "ARQ104"),
        ("ARQ401", "ARQ301"), ("ARQ402", "ARQ302"),
        ("ARQ403", "ARQ303"), ("ARQ404", "ARQ204"),
        ("ARQ501", "ARQ402"), ("ARQ501", "ARQ405"),
        ("ARQ502", "ARQ403"), ("ARQ503", "FIS101"),
        ("ARQ504", "ARQ304"), ("ARQ601", "ARQ402"),
        ("ARQ602", "ARQ404"), ("ARQ603", "ARQ502"),
        ("ARQ604", "ARQ504"), ("ARQ701", "ARQ601"),
        ("ARQ702", "ARQ401"), ("ARQ703", "ARQ603"),
        ("ARQ801", "ARQ701"), ("ARQ802", "ARQ602"),
        ("ARQ901", "ARQ801"), ("ARQ305", "ARQ304"),
        ("ARQ405", "ARQ305"), ("ARQ505", "ARQ405"),
        ("ING101", "ARQ203"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 8. Biología
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "biologia.json",
    "name": "Biología — Facultad de Ciencias Naturales",
    "courses": [
        {"code": "BIO101", "name": "Biología General", "credits": 4, "semester": 1, "area": "Fundamentos"},
        {"code": "BIO102", "name": "Laboratorio de Biología General", "credits": 2, "semester": 1, "area": "Fundamentos",
         "co_requisites": ["BIO101"]},
        {"code": "QUI101", "name": "Química General", "credits": 4, "semester": 1, "area": "Química"},
        {"code": "QUI102", "name": "Laboratorio de Química General", "credits": 2, "semester": 1, "area": "Química",
         "co_requisites": ["QUI101"]},
        {"code": "MAT101", "name": "Matemáticas I", "credits": 3, "semester": 1, "area": "Matemáticas"},
        {"code": "FIS101", "name": "Física General", "credits": 4, "semester": 1, "area": "Física"},
        {"code": "BIO201", "name": "Botánica General", "credits": 4, "semester": 2, "area": "Botánica"},
        {"code": "BIO202", "name": "Zoología General", "credits": 4, "semester": 2, "area": "Zoología"},
        {"code": "QUI201", "name": "Química Orgánica", "credits": 4, "semester": 2, "area": "Química"},
        {"code": "QUI202", "name": "Laboratorio de Química Orgánica", "credits": 2, "semester": 2, "area": "Química",
         "co_requisites": ["QUI201"]},
        {"code": "MAT102", "name": "Matemáticas II", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "EST101", "name": "Estadística", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "BIO301", "name": "Biología Celular", "credits": 4, "semester": 3, "area": "Biología Molecular"},
        {"code": "BIO302", "name": "Bioquímica", "credits": 4, "semester": 3, "area": "Biología Molecular"},
        {"code": "BIO303", "name": "Genética General", "credits": 4, "semester": 3, "area": "Genética"},
        {"code": "BIO304", "name": "Ecología General", "credits": 3, "semester": 3, "area": "Ecología"},
        {"code": "BIO401", "name": "Biología Molecular", "credits": 4, "semester": 4, "area": "Biología Molecular"},
        {"code": "BIO402", "name": "Genética de Poblaciones", "credits": 3, "semester": 4, "area": "Genética"},
        {"code": "BIO403", "name": "Fisiología Vegetal", "credits": 4, "semester": 4, "area": "Botánica"},
        {"code": "BIO404", "name": "Fisiología Animal", "credits": 4, "semester": 4, "area": "Zoología"},
        {"code": "BIO405", "name": "Microbiología", "credits": 4, "semester": 4, "area": "Microbiología"},
        {"code": "BIO501", "name": "Biología del Desarrollo", "credits": 4, "semester": 5, "area": "Biología Molecular"},
        {"code": "BIO502", "name": "Evolución", "credits": 3, "semester": 5, "area": "Genética"},
        {"code": "BIO503", "name": "Inmunología", "credits": 3, "semester": 5, "area": "Biología Molecular"},
        {"code": "BIO504", "name": "Biogeografía", "credits": 3, "semester": 5, "area": "Ecología"},
        {"code": "BIO505", "name": "Biotecnología", "credits": 4, "semester": 6, "area": "Biología Molecular"},
        {"code": "BIO506", "name": "Ecología de Ecosistemas", "credits": 3, "semester": 6, "area": "Ecología"},
        {"code": "BIO507", "name": "Biología de la Conservación", "credits": 3, "semester": 6, "area": "Ecología"},
        {"code": "BIO508", "name": "Bioinformática", "credits": 3, "semester": 6, "area": "Biología Molecular"},
        {"code": "BIO601", "name": "Biología Marina (electiva)", "credits": 3, "semester": 7, "area": "Electiva",
         "elective_group": "Electivas Biológicas", "required": False},
        {"code": "BIO602", "name": "Entomología (electiva)", "credits": 3, "semester": 7, "area": "Electiva",
         "elective_group": "Electivas Biológicas", "required": False},
        {"code": "BIO603", "name": "Micología (electiva)", "credits": 3, "semester": 7, "area": "Electiva",
         "elective_group": "Electivas Biológicas", "required": False},
        {"code": "BIO701", "name": "Práctica de Campo I", "credits": 6, "semester": 7, "area": "Práctica"},
        {"code": "BIO702", "name": "Práctica de Campo II", "credits": 6, "semester": 8, "area": "Práctica"},
        {"code": "BIO801", "name": "Trabajo de Grado", "credits": 8, "semester": 9, "area": "Investigación"},
        {"code": "HUM101", "name": "Humanidades I", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "HUM102", "name": "Humanidades II", "credits": 2, "semester": 2, "area": "Humanidades"},
        {"code": "ETI101", "name": "Bioética", "credits": 2, "semester": 5, "area": "Humanidades"},
        {"code": "BIO305", "name": "Paleontología", "credits": 3, "semester": 3, "area": "Fundamentos"},
        {"code": "BIO406", "name": "Limnología", "credits": 3, "semester": 5, "area": "Ecología"},
    ],
    "prerequisites": [
        ("BIO201", "BIO101"), ("BIO202", "BIO101"),
        ("QUI201", "QUI101"), ("MAT102", "MAT101"),
        ("BIO301", "BIO101"), ("BIO302", "QUI201"),
        ("BIO303", "BIO301"), ("BIO304", "BIO101"),
        ("BIO401", "BIO301"), ("BIO402", "BIO303"),
        ("BIO403", "BIO201"), ("BIO404", "BIO202"),
        ("BIO405", "BIO301"), ("BIO501", "BIO401"),
        ("BIO502", "BIO303"), ("BIO503", "BIO401"),
        ("BIO504", "BIO304"), ("BIO505", "BIO401"),
        ("BIO506", "BIO304"), ("BIO507", "BIO506"),
        ("BIO508", "BIO401"), ("BIO701", "BIO405"),
        ("BIO702", "BIO701"), ("BIO801", "BIO702"),
        ("HUM102", "HUM101"), ("ETI101", "BIO302"),
        ("BIO406", "BIO304"),
    ],
    "co_requisites": [
        ("BIO101", "BIO102"), ("QUI101", "QUI102"),
        ("QUI201", "QUI202"),
    ],
})

# ──────────────────────────────────────────────
# 9. Ingeniería Electrónica
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "ingenieria_electronica.json",
    "name": "Ingeniería Electrónica — Facultad de Ingeniería",
    "courses": [
        {"code": "MAT101", "name": "Cálculo Diferencial", "credits": 4, "semester": 1, "area": "Matemáticas"},
        {"code": "MAT102", "name": "Cálculo Integral", "credits": 4, "semester": 2, "area": "Matemáticas"},
        {"code": "MAT201", "name": "Cálculo Vectorial", "credits": 4, "semester": 3, "area": "Matemáticas"},
        {"code": "MAT202", "name": "Ecuaciones Diferenciales", "credits": 4, "semester": 4, "area": "Matemáticas"},
        {"code": "ALG101", "name": "Álgebra Lineal", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "FIS101", "name": "Física Mecánica", "credits": 4, "semester": 1, "area": "Física"},
        {"code": "FIS102", "name": "Física Eléctrica", "credits": 4, "semester": 2, "area": "Física"},
        {"code": "FIS103", "name": "Física de Ondas", "credits": 4, "semester": 3, "area": "Física"},
        {"code": "QUI101", "name": "Química General", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "PRO101", "name": "Programación Básica", "credits": 3, "semester": 1, "area": "Computación"},
        {"code": "ELE101", "name": "Circuitos Eléctricos I", "credits": 4, "semester": 2, "area": "Electrónica"},
        {"code": "ELE102", "name": "Laboratorio de Circuitos I", "credits": 1, "semester": 2, "area": "Electrónica",
         "co_requisites": ["ELE101"]},
        {"code": "ELE103", "name": "Circuitos Eléctricos II", "credits": 4, "semester": 3, "area": "Electrónica"},
        {"code": "ELE104", "name": "Laboratorio de Circuitos II", "credits": 1, "semester": 3, "area": "Electrónica",
         "co_requisites": ["ELE103"]},
        {"code": "ELE201", "name": "Electrónica Analógica I", "credits": 4, "semester": 3, "area": "Electrónica"},
        {"code": "ELE202", "name": "Lab. Electrónica Analógica I", "credits": 1, "semester": 3, "area": "Electrónica",
         "co_requisites": ["ELE201"]},
        {"code": "ELE203", "name": "Electrónica Analógica II", "credits": 4, "semester": 4, "area": "Electrónica"},
        {"code": "ELE204", "name": "Lab. Electrónica Analógica II", "credits": 1, "semester": 4, "area": "Electrónica",
         "co_requisites": ["ELE203"]},
        {"code": "DIG101", "name": "Electrónica Digital I", "credits": 4, "semester": 3, "area": "Digital"},
        {"code": "DIG102", "name": "Laboratorio de Digital I", "credits": 1, "semester": 3, "area": "Digital",
         "co_requisites": ["DIG101"]},
        {"code": "DIG201", "name": "Electrónica Digital II", "credits": 4, "semester": 4, "area": "Digital"},
        {"code": "DIG202", "name": "Laboratorio de Digital II", "credits": 1, "semester": 4, "area": "Digital",
         "co_requisites": ["DIG201"]},
        {"code": "SEÑ101", "name": "Señales y Sistemas", "credits": 4, "semester": 5, "area": "Procesamiento"},
        {"code": "SEÑ102", "name": "Procesamiento Digital de Señales", "credits": 4, "semester": 6, "area": "Procesamiento"},
        {"code": "CON101", "name": "Control Automático I", "credits": 4, "semester": 5, "area": "Control"},
        {"code": "CON102", "name": "Control Automático II", "credits": 4, "semester": 6, "area": "Control"},
        {"code": "CON103", "name": "Laboratorio de Control", "credits": 2, "semester": 6, "area": "Control",
         "co_requisites": ["CON102"]},
        {"code": "COM101", "name": "Comunicaciones I", "credits": 4, "semester": 5, "area": "Comunicaciones"},
        {"code": "COM102", "name": "Comunicaciones II", "credits": 4, "semester": 6, "area": "Comunicaciones"},
        {"code": "MIC101", "name": "Microcontroladores", "credits": 3, "semester": 5, "area": "Digital"},
        {"code": "MIC102", "name": "Laboratorio de Microcontroladores", "credits": 2, "semester": 5, "area": "Digital",
         "co_requisites": ["MIC101"]},
        {"code": "PRO201", "name": "Programación Avanzada", "credits": 3, "semester": 4, "area": "Computación"},
        {"code": "SIS101", "name": "Sistemas Embebidos", "credits": 4, "semester": 7, "area": "Digital"},
        {"code": "ROB101", "name": "Robótica", "credits": 4, "semester": 7, "area": "Control"},
        {"code": "RED101", "name": "Redes de Datos", "credits": 3, "semester": 6, "area": "Comunicaciones"},
        {"code": "MAT301", "name": "Matemáticas Especiales", "credits": 3, "semester": 5, "area": "Matemáticas"},
        {"code": "PRO301", "name": "Proyecto Integrador I", "credits": 4, "semester": 7, "area": "Proyecto"},
        {"code": "PRO302", "name": "Proyecto Integrador II", "credits": 4, "semester": 8, "area": "Proyecto"},
        {"code": "PRO303", "name": "Trabajo de Grado", "credits": 6, "semester": 9, "area": "Investigación"},
        {"code": "GER101", "name": "Gerencia de Proyectos Tecnológicos", "credits": 3, "semester": 8, "area": "Gestión"},
        {"code": "ELE301", "name": "Electrónica de Potencia", "credits": 4, "semester": 7, "area": "Electrónica"},
        {"code": "ELE302", "name": "Instrumentación Industrial", "credits": 3, "semester": 7, "area": "Electrónica"},
        {"code": "INT101", "name": "Inteligencia Artificial (electiva)", "credits": 3, "semester": 8,
         "area": "Electiva", "elective_group": "Electivas Avanzadas", "required": False},
        {"code": "INT102", "name": "Visión por Computador (electiva)", "credits": 3, "semester": 8,
         "area": "Electiva", "elective_group": "Electivas Avanzadas", "required": False},
    ],
    "prerequisites": [
        ("MAT102", "MAT101"), ("MAT201", "MAT102"),
        ("MAT202", "MAT201"), ("ALG101", "MAT101"),
        ("FIS102", "FIS101"), ("FIS103", "FIS102"),
        ("ELE101", "FIS102"), ("ELE101", "MAT102"),
        ("ELE103", "ELE101"), ("ELE201", "ELE101"),
        ("ELE203", "ELE201"), ("DIG101", "ELE101"),
        ("DIG201", "DIG101"), ("SEÑ101", "MAT202"),
        ("SEÑ101", "ELE103"), ("SEÑ102", "SEÑ101"),
        ("CON101", "SEÑ101"), ("CON102", "CON101"),
        ("COM101", "SEÑ101"), ("COM102", "COM101"),
        ("MIC101", "DIG201"), ("PRO201", "PRO101"),
        ("SIS101", "MIC101"), ("SIS101", "PRO201"),
        ("ROB101", "CON102"), ("RED101", "COM101"),
        ("MAT301", "ALG101"), ("PRO301", "CON102"),
        ("PRO301", "COM102"), ("PRO302", "PRO301"),
        ("PRO303", "PRO302"), ("ELE301", "ELE203"),
        ("ELE302", "ELE203"),
    ],
    "co_requisites": [
        ("ELE101", "ELE102"), ("ELE103", "ELE104"),
        ("ELE201", "ELE202"), ("ELE203", "ELE204"),
        ("DIG101", "DIG102"), ("DIG201", "DIG202"),
        ("CON102", "CON103"), ("MIC101", "MIC102"),
    ],
})

# ──────────────────────────────────────────────
# 10. Contaduría Pública
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "contaduria_publica.json",
    "name": "Contaduría Pública — Facultad de Ciencias Contables",
    "courses": [
        {"code": "CON101", "name": "Contabilidad General I", "credits": 4, "semester": 1, "area": "Contabilidad"},
        {"code": "CON102", "name": "Contabilidad General II", "credits": 4, "semester": 2, "area": "Contabilidad"},
        {"code": "ECO101", "name": "Economía General", "credits": 3, "semester": 1, "area": "Economía"},
        {"code": "MAT101", "name": "Matemáticas Básicas", "credits": 3, "semester": 1, "area": "Matemáticas"},
        {"code": "MAT102", "name": "Matemáticas Financieras", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "DER101", "name": "Derecho Comercial", "credits": 2, "semester": 1, "area": "Derecho"},
        {"code": "DER102", "name": "Derecho Laboral", "credits": 2, "semester": 3, "area": "Derecho"},
        {"code": "ADM101", "name": "Fundamentos de Administración", "credits": 3, "semester": 1, "area": "Administración"},
        {"code": "CON201", "name": "Contabilidad de Costos I", "credits": 4, "semester": 3, "area": "Contabilidad"},
        {"code": "CON202", "name": "Contabilidad de Costos II", "credits": 4, "semester": 4, "area": "Contabilidad"},
        {"code": "CON301", "name": "Contabilidad Financiera I", "credits": 4, "semester": 3, "area": "Contabilidad"},
        {"code": "CON302", "name": "Contabilidad Financiera II", "credits": 4, "semester": 4, "area": "Contabilidad"},
        {"code": "CON303", "name": "Contabilidad Financiera III", "credits": 4, "semester": 5, "area": "Contabilidad"},
        {"code": "CON401", "name": "Contabilidad de Sociedades", "credits": 3, "semester": 5, "area": "Contabilidad"},
        {"code": "CON402", "name": "Contabilidad Gubernamental", "credits": 3, "semester": 6, "area": "Contabilidad"},
        {"code": "CON403", "name": "Contabilidad Tributaria I", "credits": 3, "semester": 5, "area": "Tributaria"},
        {"code": "CON404", "name": "Contabilidad Tributaria II", "credits": 3, "semester": 6, "area": "Tributaria"},
        {"code": "CON501", "name": "Contabilidad Internacional (NIIF)", "credits": 3, "semester": 6, "area": "Contabilidad"},
        {"code": "AUD101", "name": "Auditoría General I", "credits": 3, "semester": 6, "area": "Auditoría"},
        {"code": "AUD102", "name": "Auditoría General II", "credits": 3, "semester": 7, "area": "Auditoría"},
        {"code": "AUD201", "name": "Auditoría de Sistemas", "credits": 3, "semester": 8, "area": "Auditoría"},
        {"code": "FIN101", "name": "Finanzas Corporativas", "credits": 4, "semester": 5, "area": "Finanzas"},
        {"code": "FIN102", "name": "Gestión Financiera", "credits": 3, "semester": 6, "area": "Finanzas"},
        {"code": "EST101", "name": "Estadística", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "EST102", "name": "Estadística Aplicada a la Contaduría", "credits": 3, "semester": 5,
         "area": "Matemáticas"},
        {"code": "DER201", "name": "Derecho Tributario", "credits": 3, "semester": 4, "area": "Derecho"},
        {"code": "DER202", "name": "Derecho Societario", "credits": 2, "semester": 4, "area": "Derecho"},
        {"code": "ETI101", "name": "Ética Profesional del Contador", "credits": 2, "semester": 7, "area": "Humanidades"},
        {"code": "CON601", "name": "Práctica Contable I", "credits": 4, "semester": 7, "area": "Práctica"},
        {"code": "CON602", "name": "Práctica Contable II", "credits": 4, "semester": 8, "area": "Práctica"},
        {"code": "CON603", "name": "Seminario de Investigación Contable", "credits": 3, "semester": 8,
         "area": "Investigación"},
        {"code": "CON701", "name": "Trabajo de Grado", "credits": 6, "semester": 9, "area": "Investigación"},
        {"code": "INF101", "name": "Informática Contable", "credits": 3, "semester": 3, "area": "Tecnología"},
        {"code": "INF102", "name": "Software Contable Aplicado", "credits": 3, "semester": 5, "area": "Tecnología"},
        {"code": "PRE101", "name": "Presupuesto y Evaluación de Proyectos", "credits": 3, "semester": 7,
         "area": "Finanzas"},
        {"code": "ING101", "name": "Inglés Técnico I", "credits": 2, "semester": 1, "area": "Idiomas"},
        {"code": "ING102", "name": "Inglés Técnico II", "credits": 2, "semester": 2, "area": "Idiomas"},
        {"code": "ING201", "name": "Inglés Técnico III", "credits": 2, "semester": 3, "area": "Idiomas"},
        {"code": "HUM101", "name": "Humanidades I", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "HUM102", "name": "Humanidades II", "credits": 2, "semester": 2, "area": "Humanidades"},
        {"code": "CON801", "name": "Revisoría Fiscal", "credits": 3, "semester": 8, "area": "Auditoría"},
        {"code": "CON802", "name": "Peritaje Contable", "credits": 2, "semester": 8, "area": "Auditoría"},
    ],
    "prerequisites": [
        ("CON102", "CON101"), ("MAT102", "MAT101"),
        ("CON201", "CON102"), ("CON202", "CON201"),
        ("CON301", "CON102"), ("CON302", "CON301"),
        ("CON303", "CON302"), ("CON401", "CON301"),
        ("CON402", "CON303"), ("CON403", "CON301"),
        ("CON404", "CON403"), ("CON501", "CON303"),
        ("AUD101", "CON302"), ("AUD102", "AUD101"),
        ("AUD201", "AUD102"), ("FIN101", "MAT102"),
        ("FIN101", "CON302"), ("FIN102", "FIN101"),
        ("EST102", "EST101"), ("DER201", "DER101"),
        ("DER202", "DER101"), ("CON601", "CON303"),
        ("CON602", "CON601"), ("CON603", "EST102"),
        ("CON701", "CON603"), ("INF101", "MAT101"),
        ("INF102", "INF101"), ("PRE101", "FIN101"),
        ("ING102", "ING101"), ("ING201", "ING102"),
        ("HUM102", "HUM101"), ("CON801", "AUD102"),
        ("CON802", "AUD101"),
    ],
    "co_requisites": [],
})

# ──────────────────────────────────────────────
# 11. Enfermería
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "enfermeria.json",
    "name": "Enfermería — Facultad de Ciencias de la Salud",
    "courses": [
        {"code": "ENF101", "name": "Introducción a la Enfermería", "credits": 3, "semester": 1, "area": "Fundamentos"},
        {"code": "ENF102", "name": "Historia y Filosofía de la Enfermería", "credits": 2, "semester": 1,
         "area": "Fundamentos"},
        {"code": "ANA101", "name": "Anatomía Humana", "credits": 5, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "FIS101", "name": "Fisiología Humana", "credits": 5, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "BIO101", "name": "Biología General", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "QUI101", "name": "Bioquímica", "credits": 3, "semester": 1, "area": "Ciencias Básicas"},
        {"code": "ENF201", "name": "Fundamentos del Cuidado de Enfermería", "credits": 4, "semester": 2,
         "area": "Fundamentos"},
        {"code": "ENF202", "name": "Laboratorio de Cuidado Básico", "credits": 2, "semester": 2, "area": "Fundamentos",
         "co_requisites": ["ENF201"]},
        {"code": "MIC101", "name": "Microbiología", "credits": 3, "semester": 2, "area": "Ciencias Básicas"},
        {"code": "FAR101", "name": "Farmacología General", "credits": 3, "semester": 2, "area": "Ciencias Clínicas"},
        {"code": "PSI101", "name": "Psicología General", "credits": 3, "semester": 2, "area": "Ciencias Sociales"},
        {"code": "NU101", "name": "Nutrición y Dietética", "credits": 2, "semester": 2, "area": "Ciencias Clínicas"},
        {"code": "ENF301", "name": "Enfermería Médico-Quirúrgica I", "credits": 5, "semester": 3, "area": "Clínica"},
        {"code": "ENF302", "name": "Enfermería Médico-Quirúrgica II", "credits": 5, "semester": 4, "area": "Clínica"},
        {"code": "ENF303", "name": "Enfermería Materno-Infantil I", "credits": 4, "semester": 3, "area": "Clínica"},
        {"code": "ENF304", "name": "Enfermería Materno-Infantil II", "credits": 4, "semester": 4, "area": "Clínica"},
        {"code": "ENF305", "name": "Enfermería Pediátrica", "credits": 4, "semester": 4, "area": "Clínica"},
        {"code": "ENF306", "name": "Enfermería Comunitaria I", "credits": 3, "semester": 3, "area": "Comunitaria"},
        {"code": "ENF307", "name": "Enfermería Comunitaria II", "credits": 3, "semester": 4, "area": "Comunitaria"},
        {"code": "PAT101", "name": "Patología General", "credits": 3, "semester": 3, "area": "Ciencias Clínicas"},
        {"code": "FAR102", "name": "Farmacología Clínica", "credits": 3, "semester": 3, "area": "Ciencias Clínicas"},
        {"code": "ENF401", "name": "Enfermería en Salud Mental", "credits": 4, "semester": 5, "area": "Clínica"},
        {"code": "ENF402", "name": "Enfermería en Cuidado Crítico", "credits": 4, "semester": 5, "area": "Clínica"},
        {"code": "ENF403", "name": "Enfermería Geriátrica", "credits": 3, "semester": 5, "area": "Clínica"},
        {"code": "ENF404", "name": "Administración en Enfermería", "credits": 3, "semester": 5, "area": "Gestión"},
        {"code": "EPI101", "name": "Epidemiología", "credits": 3, "semester": 4, "area": "Salud Pública"},
        {"code": "SAL101", "name": "Salud Pública", "credits": 3, "semester": 3, "area": "Salud Pública"},
        {"code": "INV101", "name": "Investigación en Enfermería", "credits": 3, "semester": 6, "area": "Investigación"},
        {"code": "ENF501", "name": "Práctica Clínica I", "credits": 8, "semester": 6, "area": "Práctica"},
        {"code": "ENF502", "name": "Práctica Clínica II", "credits": 8, "semester": 7, "area": "Práctica"},
        {"code": "ENF503", "name": "Práctica Clínica III", "credits": 8, "semester": 8, "area": "Práctica"},
        {"code": "ENF504", "name": "Trabajo de Grado", "credits": 6, "semester": 8, "area": "Investigación"},
        {"code": "ETI101", "name": "Ética Profesional y Bioética", "credits": 2, "semester": 5, "area": "Humanidades"},
        {"code": "LEG101", "name": "Legislación en Salud", "credits": 2, "semester": 6, "area": "Derecho"},
        {"code": "HUM101", "name": "Humanidades I", "credits": 2, "semester": 1, "area": "Humanidades"},
        {"code": "HUM102", "name": "Humanidades II", "credits": 2, "semester": 2, "area": "Humanidades"},
        {"code": "ENF308", "name": "Electiva Clínica I", "credits": 3, "semester": 6, "area": "Electiva",
         "elective_group": "Electivas Clínicas", "required": False},
        {"code": "ENF309", "name": "Electiva Clínica II", "credits": 3, "semester": 7, "area": "Electiva",
         "elective_group": "Electivas Clínicas", "required": False},
    ],
    "prerequisites": [
        ("ENF201", "ENF101"), ("MIC101", "BIO101"),
        ("FAR101", "FIS101"), ("PSI101", "BIO101"),
        ("ENF301", "ENF201"), ("ENF302", "ENF301"),
        ("ENF303", "ENF201"), ("ENF304", "ENF303"),
        ("ENF305", "ENF304"), ("ENF308", "ENF201"),
        ("ENF309", "ENF308"), ("PAT101", "ANA101"),
        ("FAR102", "FAR101"), ("ENF401", "ENF302"),
        ("ENF402", "ENF302"), ("ENF403", "ENF302"),
        ("ENF404", "ENF201"), ("EPI101", "SAL101"),
        ("INV101", "EPI101"), ("ENF501", "ENF302"),
        ("ENF501", "ENF305"), ("ENF502", "ENF501"),
        ("ENF503", "ENF502"), ("ENF504", "INV101"),
        ("HUM102", "HUM101"),
    ],
    "co_requisites": [
        ("ENF201", "ENF202"),
    ],
})

# ──────────────────────────────────────────────
# 12. Ingeniería Química
# ──────────────────────────────────────────────
CURRICULA.append({
    "filename": "ingenieria_quimica.json",
    "name": "Ingeniería Química — Facultad de Ingeniería",
    "courses": [
        {"code": "MAT101", "name": "Cálculo Diferencial", "credits": 4, "semester": 1, "area": "Matemáticas"},
        {"code": "MAT102", "name": "Cálculo Integral", "credits": 4, "semester": 2, "area": "Matemáticas"},
        {"code": "MAT201", "name": "Cálculo Vectorial", "credits": 4, "semester": 3, "area": "Matemáticas"},
        {"code": "MAT202", "name": "Ecuaciones Diferenciales", "credits": 4, "semester": 4, "area": "Matemáticas"},
        {"code": "ALG101", "name": "Álgebra Lineal", "credits": 3, "semester": 2, "area": "Matemáticas"},
        {"code": "EST101", "name": "Probabilidad y Estadística", "credits": 3, "semester": 4, "area": "Matemáticas"},
        {"code": "FIS101", "name": "Física Mecánica", "credits": 4, "semester": 1, "area": "Física"},
        {"code": "FIS102", "name": "Física Eléctrica", "credits": 4, "semester": 2, "area": "Física"},
        {"code": "FIS103", "name": "Física de Ondas", "credits": 4, "semester": 3, "area": "Física"},
        {"code": "QUI101", "name": "Química General I", "credits": 4, "semester": 1, "area": "Química"},
        {"code": "QUI102", "name": "Laboratorio de Química General I", "credits": 1, "semester": 1, "area": "Química",
         "co_requisites": ["QUI101"]},
        {"code": "QUI201", "name": "Química General II", "credits": 4, "semester": 2, "area": "Química"},
        {"code": "QUI202", "name": "Laboratorio de Química General II", "credits": 1, "semester": 2, "area": "Química",
         "co_requisites": ["QUI201"]},
        {"code": "QUI301", "name": "Química Orgánica I", "credits": 4, "semester": 3, "area": "Química"},
        {"code": "QUI302", "name": "Laboratorio de Química Orgánica I", "credits": 1, "semester": 3, "area": "Química",
         "co_requisites": ["QUI301"]},
        {"code": "QUI303", "name": "Química Orgánica II", "credits": 4, "semester": 4, "area": "Química"},
        {"code": "QUI304", "name": "Laboratorio de Química Orgánica II", "credits": 1, "semester": 4, "area": "Química",
         "co_requisites": ["QUI303"]},
        {"code": "QUI401", "name": "Química Analítica", "credits": 4, "semester": 3, "area": "Química"},
        {"code": "QUI402", "name": "Laboratorio de Química Analítica", "credits": 1, "semester": 3, "area": "Química",
         "co_requisites": ["QUI401"]},
        {"code": "QUI501", "name": "Fisicoquímica I", "credits": 4, "semester": 4, "area": "Química"},
        {"code": "QUI502", "name": "Fisicoquímica II", "credits": 4, "semester": 5, "area": "Química"},
        {"code": "IQ101", "name": "Introducción a la Ingeniería Química", "credits": 2, "semester": 1,
         "area": "Fundamentos"},
        {"code": "IQ201", "name": "Balances de Materia y Energía", "credits": 4, "semester": 3, "area": "Ing. Química"},
        {"code": "IQ301", "name": "Termodinámica del Equilibrio", "credits": 4, "semester": 5, "area": "Ing. Química"},
        {"code": "IQ302", "name": "Fenómenos de Transporte I", "credits": 4, "semester": 5, "area": "Ing. Química"},
        {"code": "IQ303", "name": "Fenómenos de Transporte II", "credits": 4, "semester": 6, "area": "Ing. Química"},
        {"code": "IQ401", "name": "Operaciones Unitarias I", "credits": 4, "semester": 5, "area": "Ing. Química"},
        {"code": "IQ402", "name": "Operaciones Unitarias II", "credits": 4, "semester": 6, "area": "Ing. Química"},
        {"code": "IQ403", "name": "Operaciones Unitarias III", "credits": 4, "semester": 7, "area": "Ing. Química"},
        {"code": "IQ501", "name": "Diseño de Reactores Químicos", "credits": 4, "semester": 6, "area": "Ing. Química"},
        {"code": "IQ502", "name": "Ingeniería de las Reacciones", "credits": 4, "semester": 7, "area": "Ing. Química"},
        {"code": "IQ601", "name": "Diseño de Procesos", "credits": 5, "semester": 7, "area": "Ing. Química"},
        {"code": "IQ602", "name": "Control de Procesos", "credits": 4, "semester": 7, "area": "Ing. Química"},
        {"code": "IQ701", "name": "Simulación de Procesos", "credits": 3, "semester": 8, "area": "Ing. Química"},
        {"code": "IQ702", "name": "Ingeniería Ambiental", "credits": 3, "semester": 6, "area": "Ambiental"},
        {"code": "IQ801", "name": "Gerencia de Proyectos de Ingeniería", "credits": 3, "semester": 8, "area": "Gestión"},
        {"code": "IQ802", "name": "Legislación y Seguridad Industrial", "credits": 2, "semester": 8, "area": "Derecho"},
        {"code": "IQ901", "name": "Práctica Profesional", "credits": 6, "semester": 9, "area": "Práctica"},
        {"code": "IQ902", "name": "Trabajo de Grado", "credits": 6, "semester": 10, "area": "Investigación"},
        {"code": "MAT301", "name": "Métodos Numéricos", "credits": 3, "semester": 5, "area": "Matemáticas"},
        {"code": "DIB101", "name": "Dibujo de Ingeniería", "credits": 2, "semester": 1, "area": "Ingeniería"},
        {"code": "IQ305", "name": "Materiales de Ingeniería", "credits": 3, "semester": 4, "area": "Ing. Química"},
    ],
    "prerequisites": [
        ("MAT102", "MAT101"), ("MAT201", "MAT102"),
        ("MAT202", "MAT201"), ("ALG101", "MAT101"),
        ("FIS102", "FIS101"), ("FIS103", "FIS102"),
        ("QUI201", "QUI101"), ("QUI301", "QUI201"),
        ("QUI303", "QUI301"), ("QUI401", "QUI201"),
        ("QUI501", "QUI301"), ("QUI501", "MAT201"),
        ("QUI502", "QUI501"), ("IQ201", "QUI201"),
        ("IQ201", "MAT102"), ("IQ301", "QUI502"),
        ("IQ301", "MAT202"), ("IQ302", "IQ201"),
        ("IQ302", "MAT201"), ("IQ303", "IQ302"),
        ("IQ401", "IQ201"), ("IQ402", "IQ401"),
        ("IQ403", "IQ402"), ("IQ501", "IQ302"),
        ("IQ501", "IQ301"), ("IQ502", "IQ501"),
        ("IQ601", "IQ403"), ("IQ601", "IQ502"),
        ("IQ602", "IQ303"), ("IQ701", "MAT301"),
        ("IQ701", "IQ601"), ("IQ702", "IQ303"),
        ("IQ801", "IQ601"), ("MAT301", "MAT202"),
        ("IQ305", "QUI301"),
    ],
    "co_requisites": [
        ("QUI101", "QUI102"), ("QUI201", "QUI202"),
        ("QUI301", "QUI302"), ("QUI303", "QUI304"),
        ("QUI401", "QUI402"),
    ],
})

# ──────────────────────────────────────────────
# Generación de archivos
# ──────────────────────────────────────────────

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


def build_graph(entry: Dict) -> Tuple[List[Dict], List[Dict], List[Dict]]:
    """Convierte la representación de cursos y aristas al formato JSON de PrereqFlow."""
    courses_out: List[Dict] = []
    for c in entry["courses"]:
        course_rec = {
            "code": c["code"],
            "name": c["name"],
            "credits": c["credits"],
            "semester": c.get("semester"),
            "area": c.get("area"),
            "elective_group": c.get("elective_group"),
            "required": c.get("required", True),
            "co_requisites": c.get("co_requisites", []),
            "min_completed_credits": c.get("min_completed_credits"),
            "weight": c.get("weight", 1.0),
            "difficulty": c.get("difficulty", 1.0),
            "semester_offered": c.get("semester_offered"),
            "metadata": c.get("metadata", {}),
        }
        courses_out.append(course_rec)

    prereqs_out: List[Dict] = []
    seen_prereqs: Set[Tuple[str, str]] = set()
    for course, prereq in entry.get("prerequisites", []):
        key = (course.upper().strip(), prereq.upper().strip())
        if key not in seen_prereqs and key[0] != key[1]:
            seen_prereqs.add(key)
            prereqs_out.append({"course": key[0], "prereq": key[1]})

    co_out: List[Dict] = []
    seen_co: Set[Tuple[str, str]] = set()
    for a, b in entry.get("co_requisites", []):
        a_up = a.upper().strip()
        b_up = b.upper().strip()
        key = (a_up, b_up)
        if key not in seen_co and (b_up, a_up) not in seen_co:
            seen_co.add(key)
            co_out.append({"course": a_up, "co_req": b_up})

    return courses_out, prereqs_out, co_out


def main() -> None:
    total_courses = 0
    for entry in CURRICULA:
        courses, prereqs, co_reqs = build_graph(entry)
        data = {
            "courses": courses,
            "prerequisites": prereqs,
            "co_requisites": co_reqs,
        }
        filepath = os.path.join(OUTPUT_DIR, entry["filename"])
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"[OK] {entry['filename']:40s} {len(courses):2d} cursos, {len(prereqs):2d} prereqs, {len(co_reqs):2d} co-reqs")
        total_courses += len(courses)

    print(f"\nTotal: {len(CURRICULA)} archivos generados, {total_courses} cursos en total.")


if __name__ == "__main__":
    main()
